/**:
  ros__parameters:
    use_sim_time: true
    
    common:
      lid_topic: "/livox/lidar"     # 雷达话题
      imu_topic: "/imu/data"        # IMU话题
      time_sync_en: false           
      time_offset_lidar_to_imu: 0.0 

    # ======== 【关键修改：根据真实 URDF 尺寸过滤】 ========
    preprocess:
      blind: 0.45                  

    mapping:
      extrinsic_T: [0.0, 0.0, 0.0] # 雷达到IMU的平移外参
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]  

    publish:
      path_publish_en: true         
      scan_publish_en: true         
      dense_publish_en: true        
      scan_bodyframe_pub_en: true   # 给 Nav2 局部避障用
      map_en: true
      
    # ======== 【已修复的 PCD 保存路径】 ========
    map_file_path: "/home/tao/c_program/daohang123_ws/src/fishbot_description/PCD/room.pcd"
    
    pcd_save:
      pcd_save_en: true             
      interval: -1
      