controller_manager:
  ros__parameters:
    update_rate: 100  # 控制器更新频率 Hz
    use_sim_time: true # 仿真模式必须为 true

    # 定义两个控制器：一个用于差速驱动，一个用于发布关节状态
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fishbot_diff_drive_controller:
  ros__parameters:
    # 关节名称，必须与 URDF 中的 joint name 完全一致
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # 物理参数（对应 my_robot.urdf.xacro）
    wheel_separation: 0.56  # 轮间距 (0.11 * 2)
    wheel_radius: 0.08     # 轮子半径

    # 其他参数
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    
    # 协方差设置（影响里程计精度信任度）
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: false # 是否由控制器发布 odom -> base_footprint 的 TF

    cmd_vel_timeout: 0.5
    use_stamped_vel: false